[package]
name = "zenoh-ros"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
zenoh = { version = "1.6.2", features = [
  "plugins",
  "internal",
  "unstable",
  "shared-memory",
] }
